package strings;

public class Pro3 {

	public static void main(String[] args) {
		String[]a= {
				"Counting the Number of Even and Odd Number in a Digit",
				"Swapping of 2 numbers without 3 rd variable",
				"Count Number of Digit",
				"Sum of Digits",
				"Largest of 3 Numbers",
				"Palindrome Number",
				"Reverse a Number:",
				"Prime Number or not",
				"Fibonacci Series",
				"Factorial of Number",
				"Armstrong Number",
				"Array",
				"Sum of Elements in an Array",
				"Print Even and Odd Number elements in an Array",
				"Comparing two Arrays are equal or not",
				"Missing Number in an Array",
				"Maximum and Minimum Number in Array",
				"Sort the Array in Ascending Order",
				"Sort the Array in Descending Order",
				"Print Array without duplicates",
				"Print only duplicates in the Array",
				"Reverse an Array",
				"Average of all elements in an array",
				"Copy of elements of one array in to another Array",
				"How to merge two arrays",
				"How to delete an element in an array",
				"How to print the addition of two matrices",
				"How to print the subtraction of two matrices",
				"How to print the multiplication of two matrices",
				"How to print the transpose of matrix",
				"How to print the sum of diagonal elements of a matrix",
				"String",
				"Literal String, Non Literal String, Mutable String, Immutable String",
				"Print Each Character of the String in separate line",
				"Print ASCII Code of each character of a String",
				"Print only the Uppercase Characters of a String",
				"Count the Uppercase Characters Count of a String",
				"Print only the Lowercase Characters of a String",
				"Count the Lowercase Characters Count of a String",
				"Print only the Digit Characters of a String",
				"Count the Digit Characters Count of a String",
				"Create a New String Contains Only Upper Case",
				"Create a New String with Digit First and Characters Next",
				"Create a New String with Upper Case First and Characters Next",
				"Create a New String after removing all the white spaces",
				"Program to Reverse the Case of a String",
				"Program to find the Reverse of a String",
				"Write a program to find the String is Palindrome or not",
				"Create a Program which moves each letter by 2",
				"Print each word in a separate line",
				"Print First Character of Each word",
				"Print First Two Character of an each word",
				"Print only the word starting with W",
				"Print only the word ending with le",
				"Print only the word containing o",
				"Print only the Word containing 3 Characters",
				"Print Special Words in a String",
				"Print the Longest word in the sentence",
				"Find the Word OR Exist in the String or not",
				"Count the Number of words in a Sentence",
				"Count the Number of Words ends with D",
				"Change RED with BLUE in the String",
				"Delete RED from the String",
				"Convert first letter of each word should be capital",
				"Take a sentence and change case of each alternative word",
				"Print Alternate Cases in the String",
				"String Occurrence",
				"Word Occurrence",
				"Character Occurrence",
				"Vowel Occurrence",
				"Consonant Occurrence",
				"Capital Letter Occurrence",
				"Print Number Occurrence in a String",
				"Reverse Each word in the string",
				"Vowel and Consonant Occurrence and Count",
				"Print Even Length Words in a String",
				"Reverse Words in a String",
				"Add two String",
				"Arrange the String in Ascending order",
				"Arrange the String in Descending order",
				"Print the String without Duplicates",
				"Print only Duplicate Elements in a string",
				"Print only the common elements in both the string",
				"Print only the uncommon elements in both the string",
				"Star Pattern",
				"Square Star Pattern",
				"Increasing Star Pattern",
				"Decreasing Star Pattern",
				"Right to Left Increasing Star Pattern",
				"Right to Left Decreasing Star Pattern",
				"Hill Pattern",
				"Reverse Hill Pattern",
				"Swap Two String without 3rd variable",
				"Diamond Pattern",
				"Number Pattern",
				"Different Number Left to Right (Increasing Star Pattern)",
				"Different Number Right To Left: (Decreasing Star pattern)",
				"Same number from Left to Right: (Increasing star pattern)",
				"Same number from Right to Left: (Decreasing Star Pattern)",
				

		}; 
		
		int length=a.length;
		System.out.println(length);
		
		for(String s:a) {
			
			
			System.out.println(s);
		}
		
	}
	}


